const industries = [
  "Accommodation",
  "Accounting & auditing", "Admin, photocopying & mail services",
  "Advertising & market research",
  "Ag raw materials/live animals",
  "Agicultural support/post-harvest",
  "Agricultural Processing",
  "Animal Production",
  "Apparel",
  "Architecture design & planning",
  "Arts & entertainment",
  "Athletic & fitness centers",
  "Basic metals & products",
  "Beverage serving & bars",
  "Beverages",
  "Book publishing",
  "Books or other media",
  "Call centers",
  "Chemicals & chemical products",
  "Civil engineering",
  "Cleaning products",
  "Computer & electronic products",
  "Computer programming services",
  "Computers & electronics",
  "Construction",
  "Contracting & building",
  "Data processing & hosting",
  "Deposit bank - Developed Markets",
  "Design & building",
  "Diagnostic services",
  "Education & training services",
  "Educational support",
  "Electrical equipment",
  "Employment placement & HR",
  "Engineering",
  "Environmental consulting",
  "Equity investing - Developed Markets",
  "Equity investing - Emerging Markets",
  "Event catering & related",
  "Fabricated metal products",
  "Facilities & cleaning services",
  "Film, TV & music production",
  "Financial transaction processing",
  "Fishing & aquaculture",
  "Food products",
  "Forestry & logging",
  "Funeral & related services",
  "Furniture",
  "Games & toys",
  "General retail via Internet",
  "General second-hand goods",
  "General secondary education",
  "General stores",
  "Growing non-perennial crops",
  "Growing perennial crops",
  "Hairdressing & other beauty services",
  "Health insurance",
  "Higher education",
  "Home health care",
  "Investment advising",
  "Jewelry & related articles",
  "Landscape services",
  "Leather & related products",
  "Legal activities",
  "Libraries, museums & culture",
  "Machinery & equipment",
  "Management consultant - for-profits",
  "Management consultant - nonprofits",
  "Materials recovery & recycling",
  "Medical & dental practice",
  "Medical & dental supplies",
  "Membership organizations",
  "Microfinance - Emerging Markets",
  "Mixed Farming",
  "Mobile applications",
  "Mortgage advice & brokerage",
  "Motorized vehicles",
  "Non-life insurance",
  "Non-residential social work",
  "Other business support",
  "Other credit - Developed Markets",
  "Other credit - Emerging Markets",
  "Other education",
  "Other financial services",
  "Other human health",
  "Other info service activities",
  "Other install & construction",
  "Other insurance services",
  "Other manufacturing",
  "Other non-metallic minerals",
  "Other personal services",
  "Other professional, scientific & tech",
  "Other publishing activities",
  "Other recreation",
  "Other recycling",
  "Other renewable energy installation",
  "Other retail sale",
  "Other sports",
  "Other transport equipment",
  "Other/general wholesale trade",
  "Paper & paper products",
  "Pension/retirement plans",
  "Personal care products",
  "Pharmaceutical products",
  "Photography",
  "Plant propagation",
  "Postal & courier activities",
  "Pre- & primary education",
  "Printing & recorded media",
  "Programming & broadcasting",
  "Publishing - newspapers & magazines",
  "Real estate - leased property",
  "Real estate development",
  "Real estate- fee/contract",
  "Remediation & other waste management",
  "Rent/lease: motor vehicles",
  "Rent/lease: other goods",
  "Repair: automotive",
  "Repair: Computer & home goods",
  "Restaurants & food service",
  "Rubber & plastics products",
  "Scientific R&D",
  "Securities brokerage",
  "Security & investigation",
  "Social networks & info sharing",
  "Software publishing and SaaS platforms",
  "Solar panel installation",
  "Solar power generation",
  "Spec design (non-building)",
  "Sports goods",
  "Technology-based support services",
  "Telecommunications",
  "Textiles",
  "Transportation support",
  "Travel agency & related",
  "Waste collection",
  "Waste treatment & disposal",
  "Water supply & treatment",
  "Web portals",
  "Wood & wood products"
]

const demographics = [
  "Black",
  "Employee",
  "Family",
  "Immigrant",
  "Indigenous",
  "LGBTQ",
  "Minority",
  "Person with disability",
  "Veteran",
  "Women"
];


export { industries, demographics };